name: ci

on: [push, pull_request]

jobs:

  tests:

    timeout-minutes: 40

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install Python package and dependencies
      run: pip install .[dev]

    - name: Run pytest
      run: pytest -sv
